Jason/actions and versions
arkhn/pagai pull request #65
Opened 2020-10-23 10:19 UTC by Jasopaum

## Fixes
Fixes #64

2020-10-23 14:56 UTC, simonvadee requested changes
refacto to avoid code duplication

2020-10-27 16:04 UTC, simonvadee requested changes

2020-10-27 16:04 UTC, simonvadee commented on .github/workflows/main.yml
> +  publish-oracle11:
can you do like @vmttn and split the workflow in two parts ?

2020-10-28 09:25 UTC, simonvadee commented on .github/workflows/main.yml
> +  publish-oracle11:
actually it is meant to disappear so it's fine

2020-10-28 09:27 UTC, simonvadee approved these changes

2020-10-28 10:06 UTC, vmttn approved these changes

2020-10-28 10:09 UTC, merged